# Generated by Django 5.1.6 on 2025-03-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_category', models.CharField(choices=[('Electronics', 'Electronics'), ('Property', 'Property'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Books', 'Books'), ('Others', 'Others')], default='Others', max_length=50)),
                ('item_description', models.TextField()),
                ('item_photo', models.ImageField(upload_to='images/')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
